import { useEffect, useMemo, useRef, useState } from 'react';
import { io, Socket } from 'socket.io-client';
import { ParticleField } from './ParticleField';
import { safeTheme, themes, type Theme } from './themes';
import { Bell, ChevronDown, Compass, Gift, Hash, Headphones, Image, Mic, MicOff, MonitorUp, MoreHorizontal, Palette, PhoneOff, Plus, Search, Send, Settings, Smile, Sparkles, UserPlus, Users, Volume2 } from 'lucide-react';

type User={id:string;username:string;avatar?:string;status?:string};
type Message={id:string;channel:string;text:string;user:User;createdAt:number;editedAt?:number;reactions?:Record<string,string[]>};
const demo:Message[]=[
 {id:'1',channel:'general',text:'Добро пожаловать в SA1LID VOICES ✦',user:{id:'system',username:'SA1LID'},createdAt:Date.now()-540000},
 {id:'2',channel:'general',text:'Здесь общение ощущается по-новому. Выбери тему, настрой эффекты и заходи в войс.',user:{id:'nova',username:'Nova',status:'online'},createdAt:Date.now()-210000}
];
const channels=[['Общение','general','болталка','медиа'],['Голосовые','Лаунж','Музыка']];

export function App(){
 const [theme,setTheme]=useState<Theme>(()=>safeTheme(JSON.parse(localStorage.getItem('sa1lid-theme')||'null'))); const [reduce,setReduce]=useState(matchMedia('(prefers-reduced-motion: reduce)').matches);
 const [channel,setChannel]=useState('general'),[messages,setMessages]=useState<Message[]>(demo),[draft,setDraft]=useState(''),[settings,setSettings]=useState(false),[friends,setFriends]=useState(false),[voice,setVoice]=useState(false),[muted,setMuted]=useState(false),[sidebar,setSidebar]=useState(true);
 const [me]=useState<User>({id:'local',username:'Sailid',status:'online'});const [online,setOnline]=useState(false);const socket=useRef<Socket|undefined>(undefined);
 const css=useMemo(()=>({'--accent':theme.accent,'--accent2':theme.accent2,'--bg':theme.bg,'--panel':theme.panel,'--text':theme.text,'--blur':`${theme.blur}px`,'--radius':`${theme.radius}px`,'--wallpaper':theme.wallpaper?`url("${theme.wallpaper.replace(/["\\]/g,'')}")`:'none','--wallpaper-size':theme.wallpaperFit==='repeat'?'auto':theme.wallpaperFit} as React.CSSProperties),[theme]);
 useEffect(()=>{localStorage.setItem('sa1lid-theme',JSON.stringify(theme));},[theme]);
 useEffect(()=>{const s=io({autoConnect:true});socket.current=s;s.on('connect',()=>setOnline(true));s.on('disconnect',()=>setOnline(false));s.on('message',(m:Message)=>setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m]));return()=>{s.disconnect()}},[]);
 function send(){const text=draft.trim();if(!text)return;const m:Message={id:crypto.randomUUID(),channel,text,user:me,createdAt:Date.now()};setMessages(v=>[...v,m]);socket.current?.emit('message',m);setDraft('');}
 function apply(t:Theme){setTheme(safeTheme(t));}
 function wallpaper(file?:File){if(!file)return;const r=new FileReader();r.onload=()=>setTheme(t=>({...t,id:'custom',name:'Моя тема',wallpaper:String(r.result)}));r.readAsDataURL(file)}
 return <div className={`shell ${reduce?'reduce-motion':''}`} style={css}>
  <div className="wallpaper"/><div className="aurora a"/><div className="aurora b"/><ParticleField effect={theme.effect} reduceMotion={reduce}/><div className="cursor-glow"/>
  <aside className="rail glass"><button className="brandmark"><Sparkles size={23}/></button><span className="rail-line"/><button className="server active"><span>SV</span><i>SA1LID</i></button><button className="server"><span>AN</span><i>Anime</i></button><button className="server add"><Plus size={21}/></button><div className="rail-spacer"/><button className="round"><Compass size={19}/></button><button onClick={()=>setFriends(true)} className="round"><Users size={19}/></button><button onClick={()=>setSettings(true)} className="round"><Settings size={19}/></button></aside>
  <aside className={`nav glass ${sidebar?'':'mobile-hidden'}`}>
   <div className="workspace"><div><small>ПРОСТРАНСТВО</small><b>SA1LID VOICES</b></div><button><ChevronDown size={18}/></button></div>
   <div className="nav-shortcuts"><button className="nav-action" onClick={()=>setFriends(true)}><Users size={18}/><span>Друзья</span><i>3</i></button><button className="nav-action"><Bell size={18}/><span>Входящие</span></button></div>
   <div className="channel-scroll">{channels.map(([section,...items])=><section key={section}><div className="section-title"><span>{section}</span><button><Plus size={14}/></button></div>{items.map(x=><button key={x} className={`channel ${channel===x?'active':''}`} onClick={()=>{setChannel(x);setSidebar(false)}}>{section==='Голосовые'?<Volume2 size={17}/>:<Hash size={17}/>}<span className="channel-name">{x}</span>{section==='Голосовые'&&<i className="live-pill">LIVE</i>}</button>)}</section>)}</div>
   <div className="profile"><div className="avatar online">{me.username[0]}</div><div><b>{me.username}</b><small>{online?'В сети':'Локальный режим'}</small></div><button onClick={()=>setMuted(!muted)}>{muted?<MicOff size={17}/>:<Mic size={17}/>}</button><button onClick={()=>setSettings(true)}><Settings size={17}/></button></div>
  </aside>
  <main className="chat glass">
   <header><button className="mobile-menu" onClick={()=>setSidebar(!sidebar)}><MoreHorizontal/></button><span className="hash"><Hash size={22}/></span><div><b>{channel}</b><small><i className="secure-dot"/> защищено сквозным шифрованием</small></div><div className="header-actions"><button><Search size={18}/></button><button><Bell size={18}/></button><button onClick={()=>setVoice(!voice)}><Headphones size={18}/></button><button onClick={()=>setFriends(true)}><Users size={18}/></button></div></header>
   <div className="messages"><div className="welcome"><div className="channel-orb">#</div><h1>Добро пожаловать в #{channel}</h1><p>Начало зашифрованного канала. Говорите свободно.</p></div>{messages.filter(x=>x.channel===channel).map(m=><article className="message" key={m.id}><div className="avatar">{m.user.username[0]}</div><div><div className="message-meta"><b>{m.user.username}</b><time>{new Date(m.createdAt).toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'})}</time>{m.user.id==='system'&&<em>СИСТЕМА</em>}</div><p>{m.text}</p><div className="message-tools"><button>♡</button><button>↩</button><button>•••</button></div></div></article>)}</div>
   <div className="typing"><span className="typing-avatar">N</span> Nova печатает<span>•••</span></div><div className="composer"><button title="Добавить"><Plus size={19}/></button><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`Написать #${channel}`}/><button title="Медиа"><Image size={18}/></button><button title="Подарок"><Gift size={18}/></button><button title="Эмодзи"><Smile size={19}/></button><button onClick={send} className="send" title="Отправить"><Send size={17}/></button></div>
  </main>
  <aside className="members glass"><div className="members-head"><b>Участники</b><span>4</span></div><small>В СЕТИ — 3</small>{['Nova','Aiko','Mira'].map((x,i)=><div className="member" key={x}><div className={`avatar ${i<2?'online':''}`}>{x[0]}</div><div><b>{x}</b><span>{i===0?'Слушает музыку':i===1?'Настраивает тему':'В сети'}</span></div></div>)}<small>НЕ В СЕТИ — 1</small><div className="member offline"><div className="avatar">K</div><div><b>Kiro</b><span>3 часа назад</span></div></div></aside>
  {voice&&<div className="voice-dock glass"><div className="voice-wave"><i/><i/><i/><i/></div><div><b>Лаунж</b><small>Голос подключён · 38 ms</small></div><label>Nova <input type="range" min="0" max="200" defaultValue="100"/></label><button onClick={()=>setMuted(!muted)}>{muted?<MicOff size={17}/>:<Mic size={17}/>}</button><button><Headphones size={17}/></button><button><MonitorUp size={17}/></button><button className="hang" onClick={()=>setVoice(false)}><PhoneOff size={17}/></button></div>}
  {friends&&<Modal title="Друзья" close={()=>setFriends(false)}><div className="tabs"><button className="active">Все</button><button>В сети</button><button>Ожидают</button><button>Заблокированные</button></div><div className="search">⌕ <input placeholder="Найти или добавить друга"/><button>Добавить</button></div>{['Nova','Aiko','Mira'].map(x=><div className="friend" key={x}><div className="avatar online">{x[0]}</div><div><b>{x}</b><small>@{x.toLowerCase()} · В сети</small></div><button>Сообщение</button><button>•••</button></div>)}</Modal>}
  {settings&&<Modal title="Настройки" close={()=>setSettings(false)} wide><div className="settings-grid"><nav><div className="settings-user"><div className="avatar">S</div><span><b>Sailid</b><small>Создатель</small></span></div><b>ПЕРСОНАЛИЗАЦИЯ</b><button className="active"><Palette size={16}/>Внешний вид</button><button><Volume2 size={16}/>Звуковая студия</button><button><Mic size={16}/>Голос и видео</button><button><Settings size={16}/>Конфиденциальность</button></nav><div className="settings-content"><div className="settings-title"><div><span>ВНЕШНИЙ ВИД</span><h2>Создай свою атмосферу</h2><p>Цвет, свет, движение и звук — всё под тебя.</p></div><div className="mini-preview" style={{background:`linear-gradient(135deg,${theme.bg},${theme.accent})`}}><i/><i/><i/></div></div><div className="theme-grid">{themes.map(t=><button key={t.id} onClick={()=>apply(t)} className={theme.id===t.id?'selected':''} style={{background:`radial-gradient(circle at 80% 20%,${t.accent2}55,transparent 35%),linear-gradient(145deg,${t.bg},${t.accent})`}}><span className="theme-check">✓</span><b>{t.name}</b><small>{t.effect==='none'?'Чистый стиль':t.effect}</small></button>)}</div><div className="custom-head"><div><h3>Точная настройка</h3><p>Изменения видны моментально</p></div><label className="upload-wallpaper"><Image size={16}/>Загрузить фон<input type="file" accept="image/*" onChange={e=>wallpaper(e.target.files?.[0])}/></label></div><div className="controls"><label><span>Акцент<small>{theme.accent}</small></span><input type="color" value={theme.accent.slice(0,7)} onChange={e=>setTheme(t=>({...t,id:'custom',accent:e.target.value}))}/></label><label><span>Скругление<small>{theme.radius}px</small></span><input type="range" min="8" max="32" value={theme.radius} onChange={e=>setTheme(t=>({...t,id:'custom',radius:+e.target.value}))}/></label><label><span>Глубина стекла<small>{theme.blur}px</small></span><input type="range" min="8" max="40" value={theme.blur} onChange={e=>setTheme(t=>({...t,id:'custom',blur:+e.target.value}))}/></label><label className="switch"><span>Меньше движения<small>Спокойные анимации</small></span><input type="checkbox" checked={reduce} onChange={e=>setReduce(e.target.checked)}/></label></div></div></div></Modal>}
 </div>
}
function Modal({title,close,wide,children}:{title:string;close:()=>void;wide?:boolean;children:React.ReactNode}){return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={`modal glass ${wide?'wide':''}`}><header><h2>{title}</h2><button onClick={close}>×</button></header>{children}</div></div>}
